name: Deploy to GitHub Releases

permissions:
  contents: write
  
on:
  push:
    branches:
      - master

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Get Version from Project File
              id: get-version
              shell: bash
              run: echo "version=$(grep -oE '<Version>[^<]+' VelopackTest/VelopackTest.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

            - name: Install .NET
              uses: actions/setup-dotnet@v4
              with:
                    dotnet-version: 8.0.x

            - name: Publish Application
              run: dotnet publish VelopackTest/VelopackTest.csproj -c Release -o publish -r win-x64 --self-contained true

            - name: Create Velopack Release
              shell: bash
              run: |
                dotnet tool install -g vpk
                vpk download github --repoUrl https://github.com/NXKoses/VelopackTest
                vpk pack --mainExe VelopackTest.exe -v ${{ steps.get-version.outputs.version }} -p publish --packId VelopackTest-${{ steps.get-version.outputs.version }} --channel win
                vpk upload github \
                  --repoUrl https://github.com/NXKoses/VelopackTest \
                  --token ${{ secrets.GITHUB_TOKEN }} \
                  --publish \
                  --releaseName "VelopackTest ${{ steps.get-version.outputs.version }}" \
                  --tag v${{ steps.get-version.outputs.version }}
